/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#051B36",
        "secondary-container": "#1D4F91",
        "on-tertiary-container": "#475569",
        "secondary-fixed": "#1D4F91",
        "on-surface-variant": "#475569",
        "outline-variant": "#E2E8F0",
        "surface-container-low": "#F8FAFC",
        "primary-fixed-dim": "#93C5FD",
        "on-tertiary-fixed": "#0F172A",
        "background": "#F8FAFC",
        "tertiary-fixed": "#E2E8F0",
        "primary": "#0B2E59",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#ffffff",
        "inverse-surface": "#0F172A",
        "on-secondary": "#ffffff",
        "primary-container": "#0B2E59",
        "on-primary-container": "#ffffff",
        "surface-bright": "#F8FAFC",
        "surface-container-high": "#E2E8F0",
        "inverse-on-surface": "#F8FAFC",
        "on-primary-fixed": "#ffffff",
        "on-error": "#ffffff",
        "surface": "#ffffff",
        "tertiary-container": "#163F73",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-secondary-container": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#93C5FD",
        "on-surface": "#0F172A",
        "on-error-container": "#93000a",
        "surface-variant": "#E2E8F0",
        "on-tertiary-fixed-variant": "#475569",
        "surface-container": "#F8FAFC",
        "secondary-fixed-dim": "#93C5FD",
        "on-secondary-fixed-variant": "#475569",
        "on-background": "#0F172A",
        "on-primary": "#ffffff",
        "surface-tint": "#0B2E59",
        "surface-dim": "#E2E8F0",
        "on-primary-fixed-variant": "#475569",
        "outline": "#475569",
        "secondary": "#163F73",
        "surface-container-highest": "#E2E8F0",
        "primary-fixed": "#E2E8F0",
        "tertiary-fixed-dim": "#CBD5E1"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-padding": "80px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "gutter": "24px",
        "container-max": "1280px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "indicator": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-hero": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "headline-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["36px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "indicator": ["14px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "display-hero": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
